config/routes.rb
Techlahoma::Application.routes.draw do

  get "user_group/index"
  scope path: '/buzz', controller: :buzz do
    get "/" => :index
    get "updatethevariousblogs" => :updatethevariousblogs
  end

  scope path: '/community', controller: :community do
    get "/" => :index
    get "/codeofconduct" => :codeofconduct
    get "/contributors" => :contributors
  end

  scope path: '/groups', controller: :user_group do
    get "/" => :index
    get "/index" => :index
  end

  get "profile" => "profile#index", :as => :profile
  get "sessions/new"
  get "signin" => "sessions#new", :as => :signin
  get "signout" => "sessions#destroy", :as => :signout
  match "/auth/:provider/callback" => "sessions#create", :via => [:get, :post]
  get '/auth/failure' => "sessions#omniauth_failure"

  resources :authentications, :only => [:destroy]

  namespace "api" do#, :path => "", :constraints => {:subdomain => ["api", "stageapi"]}, :default => {:format => :json} do
    get "/" => "docs#index"
      scope path: '/blog', controller: :blog do
        get '/feed' => :feed
      end
      
      scope path: '/groups', controller: :groups do
        get '/' => :list_groups
        get '/:id' => :show_group
      end
      
  end # namespace api

  root 'buzz#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

  def self.from_omniauth(auth, current_user)
    auth = where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    if current_user.nil? && auth.user.nil?
      auth.user = User.create(:name => auth.name)
      auth.save
    elsif current_user.present? && auth.user.nil?
      auth.user = current_user
      auth.save
    end
    auth
  end

  def self.create_from_omniauth(auth)
    info = auth["user_info"] || auth["info"]
    name = info["name"] rescue ""
    create! do |authentication|
      authentication.provider = auth["provider"]
      authentication.uid = auth["uid"]
      authentication.name = name
    end
  end
end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  self.table_name = 'public.blog_entries'
  belongs_to :blog_roll
  
  def self.get_recent_blogs()
    Rails.cache.fetch("recent_blogs", :expires_in => 15.minutes) {
      BlogEntry.joins(:blog_roll).select( 'blog_rolls.title as blog_title', 'blog_entries.title' ,  :entry_uri, :posted_date).order(posted_date: :desc).limit(10)
    }
  end
end

app/models/blog_roll.rb
require "googleajax"
class BlogRoll < ActiveRecord::Base
  self.table_name = 'public.blog_rolls'
  has_many :blog_entries

  def self.harvest_new_entries()
    rollin = BlogRoll.where('active_flag = true')
    rollin.each do |r|
      parse_feed_normal(r[:feed_uri], r[:id], Time.now - 3.days)
    end
  end

  def self.create(title, author, uri, feed_uri, feed_type)
      roll = BlogRoll.new
      roll.title = title
      roll.author = author
      roll.blog_uri = uri
      roll.feed_uri = feed_uri
      roll.feed_type = feed_type
      roll.save

      #back fill the last 3 months
      parse_feed_normal(roll.feed_uri, roll.id, Time.now - 3.months)
  end


  def self.parse_feed_normal(feed_uri, blog_id, datefilter)
    GoogleAjax.referrer = "techlahoma.com"

    begin
        feedinfo = GoogleAjax::Feed.load(feed_uri)
        feedinfo[:entries].each do |c|

          if c[:published_date].to_date > datefilter
            toppy = BlogEntry.where("entry_uri = ?", c[:link]).select(:id).first

            if toppy.nil?
              entry = BlogEntry.new
              entry.blog_roll_id = blog_id
              entry.title = c[:title]
              entry.entry_uri = c[:link]
              entry.posted_date = c[:published_date]
              entry.save
            end
          end#end date check
        end #end feed info loop
    end
  end

end
=begin
BlogRoll.create('Jordan Rousseau', 'Jordan Rousseau', 'http://rousseau.io/', 'http://rousseau.io/atom.xml', 'atom' )
BlogRoll.create('Groove Coder', 'Luke Crouch', 'http://groovecoder.com/', 'http://groovecoder.com/feed/', 'feed' )
Luke Crouch - http://groovecoder.com/feed/
BlogRoll.create('Buddy Lindsey', 'Buddy Lindsey', 'http://buddylindsey.com/', 'http://buddylindsey.com/feed/', 'live' )


BlogRoll.create('Devin Clark', 'Devin Clark', 'http://devin-clark.com/', 'http://devin-clark.com/rss/', 'rss' )
BlogRoll.create('Jesse Harlin', 'Jesse Harlin', 'http://www.simiansblog.com/', 'http://www.simiansblog.com/rss?containerid=52', 'word' )
http://devin-clark.com/rss/
=end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications

  def authentication_for provider
    authentications.where(:provider => provider).first
  end
end

app/models/usergroup.rb
class Usergroup < ActiveRecord::Base

end

app/controllers/api/blog_controller.rb
class Api::BlogController < ApplicationController

  def feed
    blogroll = BlogRoll.pluck(:feed_uri)#.all
    render :json => blogroll, status: 200
  end
  
  def feed
    blogroll = BlogRoll.pluck(:feed_uri)#.all
    render :json => blogroll, status: 200
  end
  
end

app/controllers/api/docs_controller.rb
class Api::DocsController < ApplicationController

  def index
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def destroy
    authentication = current_user.authentications.find(params[:id])
    authentication.destroy
    redirect_to profile_path
  end
end

app/controllers/buzz_controller.rb
class BuzzController < ApplicationController

  def index
    @blogs = BlogEntry.get_recent_blogs()
    @blogroll = BlogRoll.all
  end


  def updatethevariousblogs
    BlogRoll.harvest_new_entries()
    render text: "harvest complete", status: 200    
  end


end

app/controllers/community_controller.rb
class CommunityController < ApplicationController

  def index

  end

  def codeofconduct

  end

  def contributors

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery :except => :create
  def new
  end

  def create
    authentication = Authentication.from_omniauth(env["omniauth.auth"],current_user)
    user = authentication.user
    session[:user_id] = user.id
    redirect_to profile_path, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def omniauth_failure
  end
end

app/controllers/user_group_controller.rb
class UserGroupController < ApplicationController

  def index
    @groups = Usergroup.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			&copy; 2014 Techlahoma |
			Find us on twitter: <a href="https://twitter.com/techlahoma">follow</a> |
			Irc: Freenode - #techlahoma |
			<a href="https://github.com/techlahoma/techlahoma"> Contribute!</a>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a href="../" class="navbar-brand">Techlahoma</a>
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse" id="navbar-main">
			<ul class="nav navbar-nav">
				<li>
					<a href="/buzz">Blogs</a>
				</li>
				<li>
					<a href="/groups">User Groups</a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if current_user %>
					<li class="dropdown">
		              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="signin"> <%= current_user.name %> <span class="caret"></span></a>
		              <ul class="dropdown-menu" aria-labelledby="signin">
		                <li><%= link_to "Profile", profile_path %></li>
		                <li><%= link_to "Sign Out", signout_path %></li>
		              </ul>
		            </li>
				<% else %>
					<li><%= link_to "Sign In", signin_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Techlahoma</title>
	<meta name='viewport', content='width=device-width, initial-scale=1.0, maximum-scale=2.0'>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
		<div class="page-header" id="banner">
			<div class="row">
				<div class="col-lg-12">
					<%= yield %>
				</div>
			</div>
		</div>
	</div>

	<%= render 'layouts/footer' %>

</body>
</html>